name: Auto-Update Duplicacy CLI Docker Image

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest Duplicacy CLI version
        id: get_version
        run: |
          JSON=$(curl -s https://duplicacy.com/latest_cli_version)
          STABLE=$(echo "${JSON}" | sed -E 's/.*"stable":"([^"]+)".*/\1/')
          echo "version=${STABLE}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Duplicacy Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jasminshah/duplicacy:${{ steps.get_version.outputs.version }}
            jasminshah/duplicacy:latest
          build-args: |
            DUPLICACY_VERSION=${{ steps.get_version.outputs.version }}
